package sla.harmony.event;

public enum EventType {

	READY(),
	MESSAGE_RECEIVED(),
	
	CHANNEL_CREATE(),
	CHANNEL_UPDATE(),
	CHANNEL_DELETE(),
	
	GUILD_BAN_ADD(),
	GUILD_BAN_REMOVE(),
	GUILD_CREATE(),
	GUILD_DELETE(),
	GUILD_INTEGRATIONS_UPDATE(),
	GUILD_MEMBER_ADD(),
	GUILD_MEMBER_REMOVE(),
	GUILD_MEMBER_UPDATE(),
	GUILD_ROLE_CREATE(),
	GUILD_ROLE_DELETE(),
	GUILD_ROLE_UPDATE(),
	GUILD_UPDATE(),
	
	MESSAGE_CREATE(),
	MESSAGE_DELETE(),
	MESSAGE_UPDATE(),
	
	PRESENCE_UPDATE(),
	
	TYPING_START(),
	USER_SETTINGS_UPDATE(),
	VOICE_STATE_UPDATE(),
	
	UNKNOWN();
	
	private EventType() {
		
	}
}
